## Git에서 서로 다른 history가 충돌한 경우

작업물이 업로드 된 저장소를 pull하지 않은 상태로 새로운 작업물을 로컬에서 생성하고 push하는 경우 reject가 발생합니다.

그 이유는 로컬이 pull을 하지 않은 채로 작업을 진행하면 원격 저장소의 history에서 벗어나 작업이 진행되고, 둘이 병합을 할 수 없기 때문입니다.

원격 저장소에 존재하는 파일과 동일한 이름의 파일을 생성하더라도 history 자체가 다르기 때문에 reject가 발생합니다.

이미 원격 저장소와 다른 history를 가지므로 정상적인 pull 또한 작동하지 않습니다.

따라서, 작업을 진행하기전 로컬을 원격 저장소와 동기화 해주어야 합니다.



### 동기화를 하는 방법

작업을 하는 도중 원격 저장소와 다른 history를 갖게 되는 경우에는 다음과 같은 해결 방법이 있습니다.



#### 1. 원격 저장소와 동기화

위에서 원격 저장소와 다른 history를 갖기 때문에 정상적인 pull이 되지 않는다고 언급했습니다.

따라서, 강제로 pull을 진행시켜 주어야 하며, 다음의 옵션을 추가하여 실행할 수 있습니다.

```bash
git pull origin <branch이름> --allow-unrelated-histories
```

위 옵션을 추가하여 실행할 경우 강제로 pull이 실행되며 원격 저장소와 동기화 됩니다.



##### (1) 원격 저장소에 있는 파일과 동일한 이름의 파일을 작업하는 경우

이 경우에는 conflict가 발생하며 로컬에서 conflict를 해결하고 작업을 진행하면 됩니다.



##### (2) 원격 저장소에 없는 파일을 작업하는 경우

이 경우에는 파일에 아무런 지장이 가지 않으며 정상적으로 push를 진행할 수 있습니다.